name: modnet-v012-matbench
channels:
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - numpy=1.23.5
  - pandas=1.5.3
  - scipy=1.9.3
  - scikit-learn=0.23.2
  - pymatgen=2020.8.13
  - matminer=0.6.5
  - monty=4.0.2
  - ruamel.yaml<0.18
  - matplotlib
  - seaborn
  - shapely
  - pip:
      - tensorflow==2.10.1
      - tensorflow-probability==0.18.0
      - modnet==0.1.12
