#!/usr/bin/env bash
set -euo pipefail

DATASET="${DATASET:-matbench_phonons}"
EPOCHS="${EPOCHS:-200}"
BATCH_SIZE="${BATCH_SIZE:-64}"
NUM_WORKERS="${NUM_WORKERS:-0}"
LOG_EVERY_STEPS="${LOG_EVERY_STEPS:-50}"
EPOCH_PAUSE_SECONDS="${EPOCH_PAUSE_SECONDS:-0.0}"
HIDDEN_DIM="${HIDDEN_DIM:-64}"
KAN_HEAD_HIDDEN_DIMS="${KAN_HEAD_HIDDEN_DIMS:-8}"
MLP_HEAD_NET="${MLP_HEAD_NET:-mlp}"
KAN_HEAD_NET="${KAN_HEAD_NET:-kan}"
NUM_CONVS="${NUM_CONVS:-4}"
CONV_KAN_HIDDEN_DIM="${CONV_KAN_HIDDEN_DIM:-16}"
CONV_KAN_IMPL="${CONV_KAN_IMPL:-fastkan}"
CONV_KAN_GRID_SIZE="${CONV_KAN_GRID_SIZE:-3}"
EDGE_DIM="${EDGE_DIM:-41}"
CUTOFF="${CUTOFF:-6.0}"
ATOM_FEATURES="${ATOM_FEATURES:-}"
EDGE_FEATURES="${EDGE_FEATURES:-}"
MLP_ATOM_FEATURES="${MLP_ATOM_FEATURES:-cgcnn}"
MLP_EDGE_FEATURES="${MLP_EDGE_FEATURES:-gaussian}"
KAN_ATOM_FEATURES="${KAN_ATOM_FEATURES:-cgcnn}"
KAN_EDGE_FEATURES="${KAN_EDGE_FEATURES:-gaussian}"
LR="${LR:-3e-3}"
WEIGHT_DECAY="${WEIGHT_DECAY:-1e-5}"
MLP_LR="${MLP_LR:-}"
KAN_LR="${KAN_LR:-0.003}"
MLP_WEIGHT_DECAY="${MLP_WEIGHT_DECAY:-}"
KAN_WEIGHT_DECAY="${KAN_WEIGHT_DECAY:-0.0}"
RUN_ID="${RUN_ID:-$(date +%Y%m%d-%H%M%S)}"
OUTPUT_DIR="${OUTPUT_DIR:-benchmarks/${DATASET}-5fold-${RUN_ID}}"

mkdir -p "${OUTPUT_DIR}"

for FOLD in 0 1 2 3 4; do
  echo "=== ${DATASET} fold ${FOLD}/4, ${EPOCHS} epochs ==="
  DATASET="${DATASET}" \
  FOLD="${FOLD}" \
  EPOCHS="${EPOCHS}" \
  BATCH_SIZE="${BATCH_SIZE}" \
  NUM_WORKERS="${NUM_WORKERS}" \
  LOG_EVERY_STEPS="${LOG_EVERY_STEPS}" \
  EPOCH_PAUSE_SECONDS="${EPOCH_PAUSE_SECONDS}" \
  HIDDEN_DIM="${HIDDEN_DIM}" \
  KAN_HEAD_HIDDEN_DIMS="${KAN_HEAD_HIDDEN_DIMS}" \
  MLP_HEAD_NET="${MLP_HEAD_NET}" \
  KAN_HEAD_NET="${KAN_HEAD_NET}" \
  NUM_CONVS="${NUM_CONVS}" \
  CONV_KAN_HIDDEN_DIM="${CONV_KAN_HIDDEN_DIM}" \
  CONV_KAN_IMPL="${CONV_KAN_IMPL}" \
  CONV_KAN_GRID_SIZE="${CONV_KAN_GRID_SIZE}" \
  EDGE_DIM="${EDGE_DIM}" \
  CUTOFF="${CUTOFF}" \
  ATOM_FEATURES="${ATOM_FEATURES}" \
  EDGE_FEATURES="${EDGE_FEATURES}" \
  MLP_ATOM_FEATURES="${MLP_ATOM_FEATURES}" \
  MLP_EDGE_FEATURES="${MLP_EDGE_FEATURES}" \
  KAN_ATOM_FEATURES="${KAN_ATOM_FEATURES}" \
  KAN_EDGE_FEATURES="${KAN_EDGE_FEATURES}" \
  LR="${LR}" \
  WEIGHT_DECAY="${WEIGHT_DECAY}" \
  MLP_LR="${MLP_LR}" \
  KAN_LR="${KAN_LR}" \
  MLP_WEIGHT_DECAY="${MLP_WEIGHT_DECAY}" \
  KAN_WEIGHT_DECAY="${KAN_WEIGHT_DECAY}" \
  OUTPUT_DIR="${OUTPUT_DIR}" \
  bash scripts/run_matbench_cuda.sh
done

python scripts/summarize_matbench_results.py \
  --input-dir "${OUTPUT_DIR}" \
  --dataset "${DATASET}" \
  --expect-folds 5

echo "5-fold outputs: ${OUTPUT_DIR}"
